### ISSUE TITLE
When the home directory is not the same as the project name

### ISSUE THREAD

**Issue by wu-clan** [samuelcolvin/check-python-version#1]
Hi, I would like to ask if it can support more than just python package directory structure?
E.g.:
```
pcp
  docs
  src
    __init__.py
```
The home directory is now pcp/src, not pcp/pcp.

When setting the path to `version_file_path: src/__init__.py`, the output `✖ "src/__init__.py" is not a file`

**Comment by samuelcolvin** [comment]
Surely you just need `version_file_path: PCP/src/__init__.py`?

**Comment by samuelcolvin** [comment]
Otherwise I'll need more details to help.

**Comment by wu-clan** [comment]
done.
